### ISSUE TITLE
可以提供一下query.txt 和Gallery.txt 文件吗？

### ISSUE THREAD

**Issue by Victordeyu** [liu-xb/DIM_GLO#2]
可以提供一下query.txt 和Gallery.txt 文件吗？
使用自己生成的query和Gallery文件报错了。

**Comment by WencyTime** [comment]
抱歉，已经毕业了，没有留这两个文件。不过这两个文件可以自己写脚本生成一下哈，每个图像的名字中有一部分是代表了行人的id的。也可以参考我们[GCMT](https://github.com/liu-xb/GCMT)中数据处理方式哈，是和 [MebNet](https://github.com/YunpengZhai/MEB-Net) 完全一样的。

**Comment by liu-xb** [comment]
抱歉，已经毕业了，没有留这两个文件。不过这两个文件可以自己写脚本生成一下哈，每个图像的名字中有一部分是代表了行人的id的。也可以参考我们[GCMT](https://github.com/liu-xb/GCMT)中数据处理方式哈，是和 [MebNet](https://github.com/YunpengZhai/MEB-Net) 完全一样的。

**Comment by liu-xb** [comment]
刚刚找到了market的 gallery和query，已经上传了。
